project_structure:
    build: build/contracts
    # build: token/src/artifacts

autofetch_sources: True
dotenv: .env

networks:
  default: development
  alfajores:
    verify: False
    update_interval: 60
    
wallets:
  from_key: ${PRIVATE_KEY}

pinata_keys:
  api_key: ${API_KEY}
  secret_api_key: ${SECRET_API_KEY}    

dev_deployment_artifacts: true
